export const dataJson = [
    { code:'BR',  nameEng:"Brazilian",       nameRus: "Бразилийцы",         size: 150 ,color:'crimson'},
    { code:'AU',  nameEng:"Australian",      nameRus: "Австралийцы",        size: 250 ,color:'brown'},
    { code:'CA',  nameEng:"Canadian",        nameRus: "Канадцы",            size: 150 ,color:'blueviolet'},
    { code:'CH',  nameEng:"Chinese",         nameRus: "Китайцы",            size: 350 ,color:'indigo'},
    { code:'DE',  nameEng:"German",          nameRus: "Немцы",              size: 150 ,color:'hotPink'},
    { code:'DK',  nameEng:"Danish",          nameRus: "Датчане",            size: 150 ,color:'green'},
    { code:'ES',  nameEng:"Spanish",         nameRus: "Испанцы",            size: 450 ,color:'magenta'},
    { code:'FI',  nameEng:"Finnish",         nameRus: "Фины",               size: 120 ,color:'maroon'},
    { code:'FR',  nameEng:"Franch",          nameRus: "Французы",           size: 150 ,color:'gold'},
    { code:'GB',  nameEng:"British",         nameRus: "Англичане",          size: 110 ,color:'navy'},
    { code:'IE',  nameEng:"Irish",           nameRus: "Ирландцы",           size: 150 ,color:'olive'},
    { code:'IR',  nameEng:"Iranian",         nameRus: "Иранцы",             size: 450 ,color:'orangeRed'}, 
    { code:'NO',  nameEng:"Norwegian",       nameRus: "Норвежцы",           size: 150 ,color:'purple'},
    { code:'NL',  nameEng:"Dutch",           nameRus: "Нидерландцы",        size: 250 ,color:'red'},
    { code:'NZ',  nameEng:"New Zealand",     nameRus: "Новозеландцы",       size: 150 ,color:'darkOrange'},
    { code:'TR',  nameEng:"Turkish",         nameRus: "Турки",              size: 250 ,color:'tomato'},
    { code:'US',  nameEng:"American",        nameRus: "Американцы",         size: 50 ,color:'cadetBlue'},
]
    
//     { code:'ALL', nameEng:"All nationality", nameRus: "Все национальности", size: 150 ,color:'blue'},
